### ISSUE TITLE
Problem installing in Ubuntu 18

### ISSUE THREAD

**Issue by alfredoq** [stiglers-eponym/BeamerPresenter#14]
Good Morning,
I am following the instructions provided to install BeamerPresenter in Ubuntu 18, installed the required packages and after typing 'make' I am getting the following error:

src/draw/pathoverlay.cpp:594:10: error: ‘TabletTrackingChange’ is not a member of ‘QEvent’
     case QEvent::TabletTrackingChange:

Any idea on how to solve it?
thanks in advance for the support,
regards

Alfredo

**Comment by stiglers-eponym** [comment]
Hi,
This might be an issue with the Qt5 version you are using. QEvent::TabletTrackingChange is only available in version 5.9 or newer. Which qt version are you using? You can find out your qt version using `qmake-qt5 --version`.

**Comment by stiglers-eponym** [comment]
You could try to compile from the current git version. In commit 0eed2bc I tried to fix this problem assuming it was due to an old Qt version. But there might be further errors when trying to compile with Qt < 5.9.

**Comment by alfredoq** [comment]
Thank you very much for the prompt response. As you pointed out, the problem was related to the Qt5 version. I upgraded it to the 5.11 version and the compilation procedure passed, however now I am facing the following error message:

/usr/bin/ld: cannot find -lpulse-mainloop-glib
/usr/bin/ld: cannot find -lpulse
collect2: error: ld returned 1 exit status
Makefile:387: recipe for target 'beamerpresenter' failed
make: *** [beamerpresenter] Error 1

Any hint on where to search?

again thank you very much for the valuable support,

regards

Alfredo

**Comment by stiglers-eponym** [comment]
Interesting. I don't really know what qmake does, but it seems like in ubuntu it includes the pulse lib for pulseaudio. (In arch linux the pulse library is not included.) Have you installed pulseaudio?

**Comment by alfredoq** [comment]
yes, the pulseaudio library is installed in the system:

sudo apt-get install pulseaudio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pulseaudio is already the newest version (1:8.0-0ubuntu3.15).

**Comment by alfredoq** [comment]
I figured out the problem: I need to to install the 'libpulse-dev' that is not installed by default. After installing that the compilation finished.

**Comment by alfredoq** [comment]
I restarted the whole process, from the git cloning command. After typing the 'qmake' command, the following error is shown:

Info: creating stash file /home/fredy/Downloads/BeamerPresenter/.qmake.stash
/opt/qt511/bin/uic: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by /opt/qt511/bin/uic)
/opt/qt511/bin/uic: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /opt/qt511/bin/uic)

the  /opt/qt511/bin/uic: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 is in place, however some problem with it happens...

**Comment by alfredoq** [comment]
setting up the following solved the problem:

export PATH=/opt/qt511/lib${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/qt511/lib${PATH:+:${PATH}}

everything compiled and Beamerpresentation started! 

thank you for the support

**Comment by alfredoq** [comment]
I am trying to open a .pdf file with notes. I can see both the presentation window and the control window with the notes. However in this mode I cannot use the pen or writting tools in the control window (in the small slide image above the notes). Is that possible? or if loading notes in the control only the pen can be used in the presentation window?

**Comment by stiglers-eponym** [comment]
Usually in ubuntu libpulse-dev should be installed as a dependecy of qtmultimedia5-dev, which is listed as a dependency in the README. I therefore assume that after 0eed2bc this issue is not relevant for (many) other users and that I can close it.
