### ISSUE TITLE
Unsuccessful build on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by jonasallgeier** [stiglers-eponym/BeamerPresenter#2]
I have problems building the project. Running `qmake` gives me `qmake: could not exec '/opt/qt512/bin/qmake': No such file or directory`. I tried to use `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake` instead, but I get a long list of errors and notes starting with:

    g++ -c -pipe -O2 -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -isystem /usr/include/poppler/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o previewslide.o src/previewslide.cpp
    src/previewslide.cpp: In member function ‘virtual void PreviewSlide::renderPage(int, const QPixmap*)’:
    src/previewslide.cpp:135:44: error: ‘class Poppler::Page’ has no member named ‘index’
                     updateCache(&pixmap, page->index());
                                               ^~~~~

What can I do to resolve this problem? I don't have any Qt5 experience and little knowledge in building source code myself. Any hints would be very much appreciated!

**Comment by stiglers-eponym** [comment]
I can not reproduce the first error, but I know the origin of the second error:
The problem arises in ubuntu <= 19.04 because BeamerPresenter requires poppler >= 0.70.
You can try to upgrade poppler following this thread:
https://askubuntu.com/questions/1112856/how-to-install-poppler-0-73-on-ubuntu-18-04

**Comment by stiglers-eponym** [comment]
Additionally it seems like I need Qt >= 5.10, which is only available (as a package) for ubuntu >= 18.10 as far as I know. For ubuntu < 18.10 this is bad news, because you'd need to change BeamerPresenter or find a way to install newer versions of both Qt and poppler.

**Comment by stiglers-eponym** [comment]
I fixed BeamerPresenter such that it does not  rely on the incompatible features of poppler and Qt anymore.
It should now be possible to directly install BeamerPresenter on ubuntu >= 18.04.3

**Comment by jonasallgeier** [comment]
Thank you very much for the quick and competent response; I will retry next week!

**Comment by jonasallgeier** [comment]
works perfectly fine now, awesome!
